# Generated by Django 5.2.7 on 2026-05-07 04:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_user_follow',
                'ordering': ['-followed_at'],
                'indexes': [models.Index(fields=['follower', '-followed_at'], name='social_user_followe_ecfe5b_idx'), models.Index(fields=['followed', '-followed_at'], name='social_user_followe_162d73_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('follower', models.F('followed')), _negated=True), name='social_user_follow_not_self')],
                'unique_together': {('follower', 'followed')},
            },
        ),
    ]
