# Generated by Django 5.2.7 on 2026-05-06 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'catalog_genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('jamendo', 'Jamendo'), ('audius', 'Audius')], db_index=True, max_length=16)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('monthly_listeners', models.PositiveIntegerField(default=0)),
                ('metadata_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_artist',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['source', 'source_id'], name='catalog_art_source_731f2b_idx'), models.Index(fields=['name'], name='catalog_art_name_36791d_idx')],
                'unique_together': {('source', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('jamendo', 'Jamendo'), ('audius', 'Audius')], db_index=True, max_length=16)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('cover', models.URLField(blank=True, max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('total_tracks', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('album', 'Album'), ('single', 'Single'), ('ep', 'EP'), ('compilation', 'Compilation')], default='album', max_length=16)),
                ('metadata_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.artist')),
            ],
            options={
                'db_table': 'catalog_album',
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('jamendo', 'Jamendo'), ('audius', 'Audius')], db_index=True, max_length=16)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('track_number', models.PositiveIntegerField(blank=True, null=True)),
                ('cover', models.URLField(blank=True, max_length=500)),
                ('explicit', models.BooleanField(default=False)),
                ('bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('popularity', models.PositiveIntegerField(default=0)),
                ('isrc', models.CharField(blank=True, max_length=32)),
                ('is_unavailable', models.BooleanField(default=False)),
                ('audio_url_cached', models.URLField(blank=True, max_length=600)),
                ('audio_url_cached_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='catalog.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.artist')),
            ],
            options={
                'db_table': 'catalog_track',
                'ordering': ['-popularity', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrackGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.genre')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.track')),
            ],
            options={
                'db_table': 'catalog_track_genre',
            },
        ),
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='tracks', through='catalog.TrackGenre', to='catalog.genre'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['source', 'source_id'], name='catalog_alb_source_d2e38b_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['title'], name='catalog_alb_title_65e085_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', 'release_date'], name='catalog_alb_artist__33ce5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('source', 'source_id')},
        ),
        migrations.AlterUniqueTogether(
            name='trackgenre',
            unique_together={('track', 'genre')},
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['source', 'source_id'], name='catalog_tra_source_30af0b_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['title'], name='catalog_tra_title_d1c714_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['artist'], name='catalog_tra_artist__ae3d04_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['album', 'track_number'], name='catalog_tra_album_i_889adf_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['popularity'], name='catalog_tra_popular_56cfb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('source', 'source_id')},
        ),
    ]
