# Generated by Django 5.2.7 on 2026-05-07 03:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='track',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='catalog_track_fts_idx'),
        ),
    ]
