# Generated by Django 5.2.7 on 2026-05-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='user',
            name='is_listening_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_recent_history_public',
            field=models.BooleanField(default=False),
        ),
    ]
