# Generated by Django 5.2.7 on 2026-05-06 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='playback_state', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position_ms', models.PositiveIntegerField(default=0)),
                ('is_playing', models.BooleanField(default=False)),
                ('volume', models.FloatField(default=0.8)),
                ('is_muted', models.BooleanField(default=False)),
                ('repeat_mode', models.CharField(choices=[('off', 'Off'), ('all', 'All'), ('one', 'One')], default='off', max_length=8)),
                ('shuffle_enabled', models.BooleanField(default=False)),
                ('queue_track_ids', models.JSONField(blank=True, default=list)),
                ('history_track_ids', models.JSONField(blank=True, default=list)),
                ('context_type', models.CharField(blank=True, max_length=24)),
                ('context_id', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.track')),
            ],
            options={
                'verbose_name': 'Playback state',
                'verbose_name_plural': 'Playback states',
                'db_table': 'playback_state',
            },
        ),
        migrations.CreateModel(
            name='PlayEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ms_listened', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('search', 'Search'), ('playlist', 'Playlist'), ('album', 'Album'), ('artist', 'Artist'), ('home', 'Home'), ('queue', 'Queue'), ('track', 'Track'), ('radio', 'Radio')], default='track', max_length=24)),
                ('played_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_events', to='catalog.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Play event',
                'verbose_name_plural': 'Play events',
                'db_table': 'playback_event',
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['user', '-played_at'], name='playback_ev_user_id_1970e4_idx')],
            },
        ),
    ]
